fix: retry when getting EOF error at E2E test (#281)
This change partially resolves #210. By adding retrying logic on pod log stream initialization and port forwarding, I was able to resolve two kinds of EOF errors, which are two of the most frequent causes of E2E test failure.

More investigation notes in https://github.com/numaproj/numaflow/issues/210#issuecomment-1293627883

Error 1
```
Watching POD: simple-pipeline-watermark-cat3-0-np6xu
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-cat3-0-np6xu/main?follow=true": EOF    functional_test.go:180: Expected vertex pod log contains "Start processing udf messages"
```
and Error 2

```
functional_test.go:39: Vertex POD name: simple-pipeline-input-0-fpizv
panic: error upgrading connection: error dialing backend: EOF
```

### Testing
The following E2E test runs show in the log that the retry is getting invoked, which helps passing the E2E tests.
* Retrying on Error 1 - https://github.com/numaproj/numaflow/actions/runs/3346765321/jobs/5544895739
* Retrying on Error 2 - https://github.com/KeranYang/numaflow/actions/runs/3341257920/jobs/5532282295

Signed-off-by: Keran Yang <yangkr920208@gmail.com>